name: donowall
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.12.0
  json_serializable: ^6.7.1
  logging: ^1.2.0
  postgres: ^2.6.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
